const assert=require('node:assert/strict');
const fs=require('node:fs');
const vm=require('node:vm');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const catalogueContext={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'dist/products.js'),'utf8'),catalogueContext);
const catalogue=JSON.parse(JSON.stringify(catalogueContext.window.roundOneProducts));
const {create}=require('../dist/cart-core.js');
const core=create(catalogue);
let rows=[];
let change=core.add(rows,'gloves-01','red-black-12oz');assert.equal(change.ok,true);rows=change.rows;
rows=core.add(rows,'gloves-01','red-black-12oz').rows;assert.equal(rows.length,1);assert.equal(rows[0].quantity,2);
rows=core.add(rows,'gloves-01','red-black-16oz').rows;assert.equal(rows.length,2);
rows=core.add(rows,'pads-01','red-black-pair').rows;assert.equal(core.summary(rows).subtotalCents,33600);assert.equal(core.summary(rows).count,4);
rows=core.setQuantity(rows,'gloves-01','red-black-12oz',3).rows;assert.equal(core.summary(rows).subtotalCents,42500);
for(const quantity of [0,-1,1.5,NaN,Infinity,1000])assert.equal(core.setQuantity(rows,'gloves-01','red-black-12oz',quantity).ok,false);
rows=core.remove(rows,'gloves-01','red-black-16oz');assert.equal(core.summary(rows).count,4);assert.equal(core.summary(rows).subtotalCents,33600);
assert.equal(core.add(rows,'gloves-02','standard').ok,false);
assert.equal(core.add(rows,'unknown','standard').ok,false);
assert.equal(core.add(rows,'gloves-01','fake-variant').ok,false);
assert.equal(core.add(rows,'__proto__','anything').ok,false);
assert.deepEqual(core.normalise([null,{},'bad',{productId:'gloves-01',variantId:'red-black-12oz',quantity:-1}]),[]);
const tampered=[{productId:'bags-01',variantId:'black-4ft-30kg',quantity:2,priceCents:1,subtotal:2}];
assert.equal(core.summary(tampered).subtotalCents,39800);
assert.deepEqual(Object.keys(core.checkoutItems(tampered)[0]).sort(),['productId','quantity','variantId']);
const stockCatalogue=JSON.parse(JSON.stringify(catalogue));stockCatalogue['gloves-01'].stock=3;stockCatalogue['gloves-01'].variants[0].stock=2;
const limited=create(stockCatalogue);let limitedRows=limited.add([],'gloves-01','red-black-12oz',2).rows;
assert.equal(limited.add(limitedRows,'gloves-01','red-black-12oz').ok,false);
limitedRows=limited.add(limitedRows,'gloves-01','red-black-16oz').rows;
assert.equal(limited.add(limitedRows,'gloves-01','red-black-14oz').ok,false);
assert.equal(limited.summary([{productId:'gloves-01',variantId:'red-black-12oz',quantity:99},{productId:'gloves-01',variantId:'red-black-16oz',quantity:99}]).count,3);
stockCatalogue['gloves-01'].stock=0;assert.equal(limited.summary(limitedRows).count,0);
const repriced=JSON.parse(JSON.stringify(catalogue));repriced['bags-01'].priceCents=20000;assert.equal(create(repriced).summary(tampered).subtotalCents,40000);
assert.equal(core.summary(rows).containsPreview,true);
for(const row of [...rows])rows=core.remove(rows,row.productId,row.variantId);assert.equal(core.summary(rows).count,0);assert.equal(core.summary(rows).subtotalCents,0);
// Exercise the real persistence adapter across simulated page loads and storage events.
const saved=new Map();let denyWrites=false;
const storage={getItem:key=>saved.get(key)||null,setItem:(key,value)=>{if(denyWrites)throw Error('Storage unavailable');saved.set(key,value);}};
function page(){const handlers={};const window={roundOneProducts:catalogue,RoundOneCartCore:{create},addEventListener:(name,fn)=>(handlers[name]??=[]).push(fn),dispatchEvent:event=>(handlers[event.type]||[]).forEach(fn=>fn(event))};const context={window,localStorage:storage,CustomEvent:class{constructor(type){this.type=type;}}};vm.runInNewContext(fs.readFileSync(path.join(root,'dist/cart-state.js'),'utf8'),context);return {cart:window.RoundOneCart,window};}
const shop=page();shop.cart.add('gloves-01','red-black-14oz');shop.cart.add('gloves-01','red-black-14oz');
const refreshed=page();assert.equal(refreshed.cart.summary().count,2);assert.equal(refreshed.cart.summary().subtotalCents,17800);
const stored=JSON.parse(saved.get('round-one-cart-v1'));assert.deepEqual(Object.keys(stored.items[0]).sort(),['productId','quantity','variantId']);
refreshed.cart.remove('gloves-01','red-black-14oz');shop.window.dispatchEvent({type:'storage',key:'round-one-cart-v1'});assert.equal(shop.cart.summary().count,0);
saved.set('round-one-cart-v1','invalid json');assert.equal(page().cart.summary().count,0);
denyWrites=true;const fallback=page();const added=fallback.cart.add('pads-01','red-black-pair');assert.equal(added.ok,true);assert.equal(added.persistent,false);assert.equal(fallback.cart.summary().count,1);
console.log('Cart checks passed: add, variant merging, quantities, totals, removal, empty state, stock caps, catalogue revalidation, tampered data rejection, persistence, cross-tab sync and storage fallback.');
